// iata.js
const airlineData = {
  "airlines_flying_to_maldives": [
    { "airline": "Maldivian", "iata": "Q2" },
    { "airline": "Villa Air", "iata": "VP" },
    { "airline": "Manta Air", "iata": "NR" },
    { "airline": "beOnd", "iata": "B4" },
    { "airline": "Aeroflot", "iata": "SU" },
    { "airline": "Air Arabia", "iata": "G9" },
    { "airline": "Air Astana", "iata": "KC" },
    { "airline": "Air France", "iata": "AF" },
    { "airline": "Air India", "iata": "AI" },
    { "airline": "AirAsia", "iata": "AK" },
    { "airline": "AirAsia", "iata": "FD" },
    { "airline": "Austrian Airlines", "iata": "OS" },
    { "airline": "Azerbaijan Airlines (AZAL)", "iata": "J2" },
    { "airline": "AZUR Air", "iata": "ZF" },
    { "airline": "Manta Air", "iata": "NR" },
    { "airline": "beOnd", "iata": "B4" },
    { "airline": "Bangkok Airways", "iata": "PG" },
    { "airline": "British Airways", "iata": "BA", "alliance":"One World"},
    { "airline": "Batik Air", "iata": "ID" },
    { "airline": "Beijing Capital Airlines", "iata": "JD" },
    { "airline": "Centrum Air", "iata": "6C" },
    { "airline": "China Eastern Airlines", "iata": "MU" },
    { "airline": "Chongqing Airlines", "iata": "OQ" },
    { "airline": "Condor", "iata": "DE" },
    { "airline": "Discover Airlines", "iata": "4Y" },
    { "airline": "Edelweiss Air", "iata": "WK" },
    { "airline": "Emirates", "iata": "EK" },
    { "airline": "Etihad Airways", "iata": "EY" },
    { "airline": "FITS Air", "iata": "8F" },
    { "airline": "Flydubai", "iata": "FZ" },
    { "airline": "Greater Bay Airlines", "iata": "HB" },
    { "airline": "Gulf Air", "iata": "GF" },
    { "airline": "Hong Kong Airlines", "iata": "HX" },
    { "airline": "IndiGo", "iata": "6E" },
    { "airline": "ITA Airways", "iata": "AZ" },
    { "airline": "Malaysia Airlines", "iata": "MH", "alliance":"One World" },
    { "airline": "Neos", "iata": "NO" },
    { "airline": "Qatar Airways", "iata": "QR", "alliance":"One World" },
    { "airline": "Saudia", "iata": "SV" },
    { "airline": "Sichuan Airlines", "iata": "3U" },
    { "airline": "Singapore Airlines", "iata": "SQ", "alliance":"Star Alliance"  },
    { "airline": "SriLankan Airlines", "iata": "UL", "alliance":"One World" },
    { "airline": "Thai AirAsia", "iata": "FD" },
    { "airline": "Turkish Airlines", "iata": "TK" },
    { "airline": "US-Bangla Airlines", "iata": "BS" },
    { "airline": "Virgin Atlantic", "iata": "VS" },
    { "airline": "XiamenAir", "iata": "MF" }
  ]
};

// Make it globally available
window.airlineData = airlineData;
